data:
 #path: '../../datasets/mnist8x8/mnist8x8'
 #path: '../../datasets/mnist8pca_dig35/mnist8pca_dig35'
 #path: '../../datasets/mnist8x8/mnist8x8'
 path: '../../datasets/fashion8x8/fashion8x8'
 #path: '../../datasets/kmnist8x8/kmnist8x8'
 val_split: 0.166 #0.2857
 list_digits: [[[1, 4, 5, 7, 8], [0, 2, 3, 6, 9]]]                     # list of pairs or one pair
 list_batch_sizes: [250]                  # list or list of single
 execute_batch_size: 250
 eval_batch_size_factor: 20
 load_from_file: True
 data_im_size: [8,8]
 sample_size: 5000000             # int or None
 feature_dim: 2
 use_8x8_pixel_dict: True

meta:
 set_visible_gpus: True
 visible_gpus: '1'
 set_memory_growth: True
 random_seed: 42
 list_num_anc: [1]                # list or list of single
 num_repeat: 5
 auto_epochs:
  enabled: False
  criterion: 0.005
  num_match: 10
  trigger: 60

 list_epochs: [100]                        # list or list of single
 list_devices: True

 deph:
  data: False
  network: True
  p: [0, 0.2, 0.4, 0.6, 0.8, 1]

tree:
 param:
  init_mean: 0
  init_std: [0.5, 0.4, 0.3, 0.2, 0.2, 0.1]

 opt:
  opt: 'adam'
  adam:
   user_lr: True
   lr: [0.005]

  spsa:
   a: 28
   b: 33
   A: 7.41
   s: 1.13
   t: 0.658
   gamma: 0.882


