data:
 #path: '../../datasets/mnist8by8/mnist8by8'
 path: '../../datasets/mnist8pca_dig27/mnist8pca_dig27'
 val_split: 0.16 #0.2857
 list_digits: [[2,7]]                     # list of pairs or one pair
 list_batch_sizes: [250]                  # list or list of single
 execute_batch_size: 250
 eval_batch_size_factor: 200
 load_from_file: True
 data_im_size: [8,1]
 sample_size: 700000              # int or None
 feature_dim: 2
 use_8by8_pixel_dict: True

meta:
 set_visible_gpus: True
 visible_gpus: '1'
 set_memory_growth: True
 random_seed: 42
 list_num_anc: [0]                # list or list of single
 num_repeat: 1
 auto_epochs:
  enabled: False
  criterion: 0.005
  num_match: 10
  trigger: 60

 list_epochs: [100]                        # list or list of single
 list_devices: True

 deph:
  data: True
  network: True
  p: [0]

tree:
 param:
  init_mean: 0
  init_std: [0.01]

 opt:
  opt: 'adam'
  adam:
   user_lr: True
   lr: [0.005]

  spsa:
   a: 28
   b: 33
   A: 7.41
   s: 1.13
   t: 0.658
   gamma: 0.882


