data:
 #path: '../../datasets/mnist8by8/mnist8by8'
 #path: '../../datasets/mnist8pca_dig35/mnist8pca_dig35'
 path: '../../datasets/fashion8by8/fashion8by8'
 val_split: 0.2 #0.2857 #0.16
 list_digits: [[5,9]]                     # list of pairs or one pair
 list_batch_sizes: [250]                  # list or list of single
 execute_batch_size: 250
 eval_batch_size_factor: 5000
 load_from_file: True
 data_im_size: [8,8]
 sample_size: 10000              # int or None
 feature_dim: 2
 use_8by8_pixel_dict: True

meta:
 set_visible_gpus: False
 visible_gpus: '3'
 set_memory_growth: False
 random_seed: 42
 list_num_anc: [2]                # list or list of single
 num_repeat: 10
 auto_epochs:
  enabled: False
  criterion: 0.005
  num_match: 10
  trigger: 60

 list_epochs: [120]                        # list or list of single
 list_devices: True

 deph:
  data: True
  network: True
  p: [0, 0.2, 0.4, 0.6, 0.8, 1]

tree:
 param:
  init_mean: 0
  init_std: [0.005, 0.01, 0.03, 0.07, 0.1, 0.3]

 opt:
  opt: 'adam'
  adam:
   user_lr: True
   lr: [0.005, 0.005, 0.005, 0.015, 0.015, 0.015]

  spsa:
   a: 28
   b: 33
   A: 7.41
   s: 1.13
   t: 0.658
   gamma: 0.882


