data:
 path: '../mnist8by8/mnist8by8'
 val_split: 0
 list_digits: [[3,5]]                     # list of pairs or one pair
 list_batch_sizes: [100]                  # list or list of single
 load_from_file: False
 data_im_size: [4,4]
 list_data_bd_dim: [2]            # list or list of single
 sample_size: 1000                # int or None

meta:
 num_repeat: 1
 auto_epochs:
  enabled: False
  criterion: 0.005
  num_match: 7
  trigger: 10

 list_epochs: [5]                        # list or list of single
 log_device_placement: True
 list_devices: True
 gpu: True

tree:
 param:
  init_mean: 0
  init_std: 1

 list_vir_bd_dim: [2]             # list or list of single
 num_anc: 0

 loss: 'l2'                               # 'l2', 'log', 'l1'
 deph:
  only_input: False
  list_deph: [0]                        # list or list of single, p = 0 / 1 makes sense

 opt:
  opt: 'adam'                          # 'sgd', 'adam', 'rmsprop'
  adam:
   show_grad: False
   show_hess: False

  sgd:
   step_size: 0.01

  rmsprop:
   learning_rate: 0.001

