data:
 #path: '../mnist4by4/mnist4by4'
 path: '../mnist8pca/mnist8pca'
 val_split: 0 #0.2857
 list_digits: [[3,5]]                     # list of pairs or one pair
 list_batch_sizes: [250]                  # list or list of single
 execute_batch_size: 250
 eval_batch_size_factor: 5
 load_from_file: True
 data_im_size: [4,2]
 sample_size: 5000                        # int or None
 feature_dim: 2
 use_4by4_pixel_dict: True

meta:
 set_visible_gpus: True
 visible_gpus: '1'
 set_memory_growth: False
 random_seed: 42
<<<<<<< HEAD
 list_num_anc: [1]                # list or list of single
 num_repeat: 3
=======
 list_num_anc: [0]                # list or list of single
 num_repeat: 1
>>>>>>> 0bd1c9e262f1537114947936fc5e5b959568ad77
 auto_epochs:
  enabled: False
  criterion: 0.005
  num_match: 10
  trigger: 60

 list_epochs: [60]                        # list or list of single
 list_devices: True

 deph:
  data: True
  network: True
  p: [1]

tree:
 param:
  init_mean: 0
<<<<<<< HEAD
  init_std: [0.01, 0.05, 0.1, 0.5, 1]
=======
  init_std: [0.01]
>>>>>>> 0bd1c9e262f1537114947936fc5e5b959568ad77

 opt:
  opt: 'adam'
  adam:
   user_lr: True
   lr: [0.005]

  spsa:
   a: 28
   b: 33
   A: 7.41
   s: 1.13
   t: 0.658
   gamma: 0.882


