data:
 path: '../mnist4by4/mnist4by4'
 val_split: 0 #0.2857
 list_digits: [[3,5]]                     # list of pairs or one pair
 list_batch_sizes: [250]                  # list or list of single
 execute_batch_size: 250
 eval_batch_size_factor: 20
 load_from_file: True
 data_im_size: [4,4]
 sample_size: 1000           # int or None
 feature_dim: 2
 use_8by8_pixel_dict: True

meta:
 set_memory_growth: True
 random_seed: 42
 list_num_anc: [0]                # list or list of single
 num_repeat: 1
 auto_epochs:
  enabled: False
  criterion: 0.005
  num_match: 10
  trigger: 60

 list_epochs: [100]                        # list or list of single
 list_devices: True

 deph:
  data: True
  network: True
  p: [1]

tree:
 param:
  init_mean: 0
  init_std: [0.1]

 opt:
  opt: 'adam'
  adam:
   user_lr: True
   lr: [0.005]

  spsa:
   a: 28
   b: 33
   A: 7.41
   s: 1.13
   t: 0.658
   gamma: 0.882


