data:
 #path: '/home/haoranliao/dephased_ttn_project/mnist8by8_exp/mnist8by8'
 path: '/home/qc_whaley/dephased_ttn_project/mnist8by8_exp/mnist8by8'
 val_split: 0
 list_digits: [[3,5]]                     # list of pairs or one pair
 list_batch_sizes: [250]                 # list or list of single
 grad_accumulation: True
 execute_batch_size: 125
 eval_batch_size_factor: 2
 load_from_file: True
 data_im_size: [8,8]
 sample_size: 5000              # int or None
 feature_dim: 2
 use_8by8_pixel_dict: True

meta:
 set_visible_gpus: False
 visible_gpus: '1'
 set_memory_growth: False
 random_seed: 42
 list_num_anc: [3]                # list or list of single
 num_repeat: -1
 auto_epochs:
  enabled: False
  criterion: 0.005
  num_match: 10
  trigger: 60

 list_epochs: []                        # list or list of single
 list_devices: True

 deph:
  data: True
  network: True
  p: [1]

tree:
 param:
  init_mean: 0
  init_std: -1

 opt:
  opt: 'adam'
  adam:
   user_lr: True
   lr: 0.0001

