data:
 path: '../../../mnist8by8/mnist8by8'
 val_split: 0
 list_digits: [[3,5]]                     # list of pairs or one pair
 list_batch_sizes: [250]                  # list or list of single
 sub_batch_size: 250
 distributed: True
 eval_batch_size_factor: 1
 load_from_file: True
 data_im_size: [8,8]
 sample_size: 5000                # int or None
 feature_dim: 2

meta:
 set_visible_gpus: False
 visible_gpus: '1'
 set_memory_growth: False
 random_seed: 42
 list_num_anc: [4]                # list or list of single
 num_repeat: 1
 early_stop:
  enabled: False
  criterion: 0.005
  num_match: 10
  trigger: 20

 list_epochs: [80]                        # list or list of single
 list_devices: True

 deph:
  data: True
  network: True
  p: [0.0, 0.0, 1.0, 1.0]

tree:
 param:
  init_mean: 0
  init_std: [0.1, 0.01, 0.001, 0.0001]
 opt:
  opt: 'adam'
  adam:
   user_lr: True
   lr: 0.005

