data:
 path: '../../mnist8by8/mnist8by8'
 val_split: 0
 list_digits: [[3,5]]                     # list of pairs or one pair
 list_batch_sizes: [50]                  # list or list of single
 load_from_file: False
 data_im_size: [4,4]
 sample_size: 1000                # int or None
 feature_dim: 2

meta:
 list_num_anc: [1]                # list or list of single
 num_repeat: 1
 auto_epochs:
  enabled: False
  criterion: 0.005
  num_match: 7
  trigger: 10

 list_epochs: [50]                        # list or list of single
 list_devices: True

 deph:
  data: True
  network: True
  p: [1]

tree:
 param:
  init_mean: 0
  init_std: 0.1

 opt:
  opt: 'adam'                          # 'adam'
  adam:
   show_grad: False
   show_hess: False

