data:
 path: '../../mnist8by8/mnist8by8'
 val_split: 0
 list_digits: [[3,5]]                     # list of pairs or one pair
 list_batch_sizes: [250]                  # list or list of single
 execute_batch_size: 250
 eval_batch_size_factor: 3
 load_from_file: True
 data_im_size: [8,8]
 sample_size: 5000              # int or None
 feature_dim: 2
 use_8by8_pixel_dict: True

meta:
 set_memory_growth: False
 random_seed: 42
 list_num_anc: [3]                # list or list of single
 num_repeat: 5
 auto_epochs:
  enabled: False
  criterion: 0.005
  num_match: 10
  trigger: 60

 list_epochs: [100]                        # list or list of single
 list_devices: True

 deph:
  data: True
  network: True
  p: [0.0, 0.2, 0.4, 0.6, 0.8, 1.0]

tree:
 param:
  init_mean: 0
  init_std: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]

 opt:
  opt: 'adam'
  adam:
   user_lr: True
   lr: [0.005, 0.005, 0.005, 0.005, 0.005, 0.005]
<<<<<<< HEAD
=======
=======
<<<<<<< HEAD
   lr: [0.005, 0.005, 0.005, 0.005, 0.005, 0.005]
=======
   lr: [0.025, 0.025, 0.025, 0.025, 0.025, 0.025]
>>>>>>> 6ab8fed815d763eef0b8132988eddfa8a0b1c12f
>>>>>>> e53cb36996efc7e66a071a06b53665766d6c5fb3
>>>>>>> 823d49d6bcaba2606cc671ff09ee6eaab12645d7

