data:
 path: '../../mnist8by8/mnist8by8'
 val_split: 0
 list_digits: [[3,5]]                     # list of pairs or one pair
 list_batch_sizes: [250]                  # list or list of single
 execute_batch_size: 250
 eval_batch_size_factor: 6
 load_from_file: True
 data_im_size: [8,8]
 sample_size: 5000                # int or None
 feature_dim: 2

meta:
 set_memory_growth: True
 random_seed: 42
<<<<<<< HEAD
 list_num_anc: [2]                # list or list of single
=======
 list_num_anc: [0]                # list or list of single
>>>>>>> 52f5df1876c36e7d4d3f11eb064e3f1424c606c2
 num_repeat: 5
 auto_epochs:
  enabled: False
  criterion: 0.005
  num_match: 10
  trigger: 60

 list_epochs: [100]                        # list or list of single
 list_devices: True

 deph:
  data: True
  network: True
  p: [0.0, 0.2, 0.4, 0.6, 0.8, 1.0]

tree:
 param:
  init_mean: 0
  init_std: 0.01

 opt:
  opt: 'adam'
  adam:
   user_lr: False
   lr: 0.0001

